### ISSUE TITLE
Publish new version

### ISSUE THREAD

**Issue by danielhusar** [FormidableLabs/react-live#101]
Hey!

Looks like the latest version on npm is `1.11.0` while the master branch on github still have `1.10.0` in package.json.

More importantly, the `1.11.0` version from npm don't have the KeyType fix:

`react-live.d.ts` content in `1.11.0` from npm:
```ts
// Helper types
type Diff<T extends string, U extends string> = ({ [P in T]: P } & { [P in U]: never } & { [x: string]: never })[T]
type Omit<T, K extends keyof T> = Pick<T, Diff<keyof T, K>>
```

`react-live.d.ts` here in master
https://github.com/FormidableLabs/react-live/blob/master/typings/react-live.d.ts#L7

Would it be possible to publish new version with fixed typings? My project is failing with 
```ts
node_modules/react-live/typings/react-live.d.ts:8:48 - error TS2344: Type 'keyof T' does not satisfy the constraint 'string'.
  Type 'string | number | symbol' is not assignable to type 'string'.
    Type 'number' is not assignable to type 'string'.

8 type Omit<T, K extends keyof T> = Pick<T, Diff<keyof T, K>>
                                                 ~~~~~~~
```

Which is fixed in github master.

Thanks for this great library, I love it!

**Comment by kitten** [comment]
Yes, we can publish a new version on Monday 🙌 thanks for the heads up!
