### ISSUE TITLE
'tokTypes' undefined when react-live used in GatsbyV2

### ISSUE THREAD

**Issue by souporserious** [FormidableLabs/react-live#104]
Apologies if this is a duplicate of #102, I also wasn't sure where to post about this issue. I haven't been able to find any information on how to fix it 😥. I'm trying to use react-live with the latest Gatsby and keep getting this error:

![image](https://user-images.githubusercontent.com/2762082/47230306-c5a40180-d37e-11e8-963d-8899297de4d9.png)

From searching around, it seems that it may be related to buble, but even if I downgrade to an older version like #102 discussed, I'm still facing the same issue. Is there something in Gatsby maybe that should be configured in Webpack? I get the error above by using a simple Gatsby starter, installing react-live and just importing the library. I'm at a loss, any help is greatly appreciated 🙏

**Comment by souporserious** [comment]
Following what the React docs site is doing for now and locking to version `1.8.0-0` this seems to get rid of the issue above.

**Comment by jimmylee** [comment]
I was also experiencing this issue in a different context.

<img width="496" alt="screen shot 2018-10-20 at 10 49 12 am" src="https://user-images.githubusercontent.com/310223/47260044-936ece80-d468-11e8-80cc-d49ee2ddc7d8.png">

**Temporary Solution**
I can confirm that locking to version `1.8.0-0` resolved it for now, in case anyone else is having this issue after a clean `npm install`

**Comment by kitten** [comment]
This is likely not going to be an issue in v2 as react-live will us prism-react-renderer by default :)
