### ISSUE TITLE
useState is not defined

### ISSUE THREAD

**Issue by tgrecojs** [FormidableLabs/react-live#114]
Running into an error trying to use the hooks api with react-live. currently i get `useState` is not defined display as an error. I had a demo of it in codesandbox that i'll link to below. I ran into the issue trying to add it to a next.js application but the code-sandbox is using create-react-app as i wasn't sure if it might've, could've ben a ssr thing. i'm not sure if updating react might be the solution but that'd be great if so 😄

[codesandbox demo](https://codesandbox.io/s/1o5kwq77n3)

#### Screenshot of error in demo

<img width="853" alt="screen shot 2019-02-18 at 5 48 41 am" src="https://user-images.githubusercontent.com/6646552/52945954-ec7c3f80-3340-11e9-9104-1dc0a2f4f3eb.png">

**Comment by sofiapoh** [comment]
Hi! This is due to `react-live` still being on react version which doesn't have hooks, it will be fixed #113 which will hopefully get released soon!

**Comment by kitten** [comment]
Actually, if you use a `react` version that's new enough you just have to use `React.useState`. Like with `React.Component` `react-live` only exposes `React` in its context, but nothing else by default.

You can obviously pass in more yourself but by default you'll only have the complete `React` variable :)

**Comment by tgrecojs** [comment]
Awesome! Thanks so much for getting back to me so quickly @kitten ... you rock 💪

**Comment by Ashley-Harris** [comment]
Thank you @kitten!

**Comment by OcampoPythonZen** [comment]
Great

**Comment by CooingJugo77** [comment]
Thank you so much. That just saved my whole google clone app

**Comment by ahmedbanihanibh** [comment]
Thank you @kitten :)
