### ISSUE TITLE
How to use prism-react-renderer in Live provider

### ISSUE THREAD

**Issue by spences10** [FormidableLabs/react-live#120]
Hi, I'm using both `prism-react-renderer` and `react-live` in a Gatsby site that uses Mdx

I have a code highlighting module that I'm using the nice themes you can plug into `Highlight` from `prism-react-renderer` and I'm also using `react-live` for Mdx hotness.

My issue is that I want to have a consistent theme across the two but can't figure out how to incorporate the theme into any of the components from `react-live` @kitten 

Are the two compatible?

Here's the component I'm using them in: https://github.com/spences10/blog.scottspence.me/blob/fa1a48c7a780309e9cc42d646b5a5491e8c66da2/src/components/Code.js#L1-L58

**Comment by kitten** [comment]
We're currently working on releasing a new major release of react-live which will be using prism-react-renderer :)
