### ISSUE TITLE
onChange called twice in LiveEditor

### ISSUE THREAD

**Issue by viczam** [FormidableLabs/react-live#127]
https://github.com/FormidableLabs/react-live/blob/master/src/components/Editor/index.js#L62

It's called once in `updateContent` by `onValueChange` and then is called again by `react-simple-code-editor` because is spread with the rest of props in render.

**Comment by sofiapoh** [comment]
I've just released a patch with #132 which should fix this, let me know if there are still some problems!

**Comment by viczam** [comment]
works great now, thank you!
