### ISSUE TITLE
Controlled code props is not sync properly in 2.0.0

### ISSUE THREAD

**Issue by ivan-dalmet** [FormidableLabs/react-live#130]
react-live: 2.0.0

When editing the code from outside by passing it with the `code` property instead of using the built in LiveEditor, the rendering display the code with 1 input late.
![docz-playground-edition-bug](https://user-images.githubusercontent.com/9749061/55347716-b4c2f480-54b5-11e9-8b9f-be78c2aea281.gif)

You can see the Docz implementation here --> https://github.com/pedronauck/docz/blob/master/core/docz-theme-default/src/components/ui/Playground/index.tsx
(issue link in the docz repo: https://github.com/pedronauck/docz/issues/752)

If we rollback to the 1.12.0 this bug no longer exists.

Any idea why?

**Comment by sofiapoh** [comment]
Hi, I think this is related to #127, I'll try to get a fix in asap!

**Comment by sofiapoh** [comment]
I've just released a patch with #132 which should fix this, let me know if there are still some problems!
