### ISSUE TITLE
Tiny display disorder while coping and pasting all codes in editor in the demo page

### ISSUE THREAD

**Issue by Terry-Su** [FormidableLabs/react-live#131]
Hi, while testing codes on the demo page, encountered a display order when I copied all codes in editor and pasted them in the editor again:
![image](https://user-images.githubusercontent.com/23733477/55474704-698b1c00-5644-11e9-9fbe-c61fbba3e5f1.png)
Although it will recover after pressing `esc`.
Just a reminder. And react-live is really a very cool tool!

**Comment by sofiapoh** [comment]
Looks like we still have the old version on `react-live` on the demo, checked this locally and it doesn't seem to be an issue with `v.2.0`, I'll get the demo updated ASAP!

**Comment by kitten** [comment]
I've just updated the demo site, so this should work now 👍
