### ISSUE TITLE
Release 2.1.0 to npm

### ISSUE THREAD

**Issue by skawaguchi** [FormidableLabs/react-live#144]
Thanks so much for the awesome library! Would it be possible to release 2.1.0 to npm? [npm](https://www.npmjs.com/package/react-live) is still at 2.0.1 as the latest.

**Comment by skawaguchi** [comment]
I just noticed that 2.1.0 was just merged. Maybe this is a CI job thing and this will show up in npm tomorrow? If so, sorry to bother you.

**Comment by sofiapoh** [comment]
Sorry, this was our mistake! The latest version is on npm now :)

**Comment by skawaguchi** [comment]
Closing because this is resolved, although there's a bug in 2.1.0. I mentioned it in #139.
