### ISSUE TITLE
Bundle size discrepancy

### ISSUE THREAD

**Issue by wagerfield** [FormidableLabs/react-live#149]
The React Live readme has a couple of badges that say that it's **31.6 kB** and **28 kB gzipped**.

I'm using React Live in a React Static site and am seeing much larger bundles than this and would like to know if there's something I should be doing to reduce them.

I've created a bare bones example for you to test and included some notes and instructions in the readme:

https://github.com/wagerfield/react-static-live

Any help on this would be much appreciated.

**Comment by danielstocks** [comment]
@wagerfield I'm having the same issue. I ran a test with a [stripped down Webpack setup](https://github.com/danielstocks/react-live-webpack-test).

Bundle size w/ React & React-DOM
```
Version: webpack 4.33.0
Time: 1655ms
Built at: 06/05/2019 11:02:37 AM
       Asset       Size  Chunks             Chunk Names
./index.html  174 bytes          [emitted]
     main.js    117 KiB       0  [emitted]  main
Entrypoint main = main.js
[7] (webpack)/buildin/global.js 472 bytes {0} [built]
[8] ./src/index.js + 1 modules 292 bytes {0} [built]
    | ./src/index.js 158 bytes [built]
    | ./src/app.js 124 bytes [built]
```
The gzipped size is of main.js (according to webpack-bundle-analyzer) is 37.41 kb

Bundle after adding react-live.
```
Version: webpack 4.33.0
Time: 5000ms
Built at: 06/05/2019 11:06:02 AM
       Asset       Size  Chunks                    Chunk Names
./index.html  174 bytes          [emitted]
     main.js    793 KiB       0  [emitted]  [big]  main
Entrypoint main [big] = main.js
  [2] (webpack)/buildin/global.js 472 bytes {0} [built]
 [10] (webpack)/buildin/module.js 497 bytes {0} [built]
 [45] ./node_modules/regenerate-unicode-properties sync ^\.\/.*\.js$ 12.9 KiB {0} [optional] [built]
[472] ./src/index.js + 3 modules 448 KiB {0} [built]
      | ./src/index.js 140 bytes [built]
      | ./src/app.js 438 bytes [built]
      |     + 2 hidden modules
    + 469 hidden modules
```
The gzipped size is of main.js (according to webpack-bundle-analyzer) is now 209.19 kb

By looking at the webpack-bundle-analyzer it seems that the `./node_modules/regenerate-unicode-properties` is a major contributor to the bundle size (57.64 KB gzipped)

<img width="1552" alt="Screenshot 2019-06-05 at 11 17 30" src="https://user-images.githubusercontent.com/52788/58945147-97dfc180-8783-11e9-92a2-c00080d99aa2.png">

**Comment by kitten** [comment]
We don't bundle Buble onto our reported size so you'll have to add that on top unfortunately.

Buble also recently merged support for transpiling ESnext RegExp expressions, which adds the rather large unicode dependency you're seeing.

If you don't care about this RegExp support, and I think it's a rather use case personally, I do have a fork of Buble that is a little smaller due to its removal: https://www.npmjs.com/package/@philpl/buble

**Comment by danielstocks** [comment]
Thanks for the clarification @kitten.

And for reference, the above test was run with the Webpack `--production` flag https://github.com/danielstocks/react-live-webpack-test/blob/master/package.json#L7

**Comment by kitten** [comment]
also before I forget, you can find the source of the fork with the added commits here: https://github.com/kitten/buble

**Comment by kitten** [comment]
@danielstocks @wagerfield The PR here adds some notes to the readme on the bundle size you can expect and how to reduce it; since we can't actually do much to reduce our bundle size, I think this is a good compromise: https://github.com/FormidableLabs/react-live/pull/150

cc @sofiapoh

**Comment by danielstocks** [comment]
Thanks for the quick response and clarification @kitten & @sofiapoh
