### ISSUE TITLE
Is it possible to send in a component to live edit?

### ISSUE THREAD

**Issue by conradj** [FormidableLabs/react-live#154]
Is being able to send in a component to live edit a reasonable use case? Something like:

```jsx
import {
  LiveProvider,
  LiveEditor,
  LiveError,
  LivePreview
} from 'react-live'

import myComponent from './mycomponent'

<LiveProvider code={myComponent}>
  <LiveEditor />
  <LiveError />
  <LivePreview />
</LiveProvider>

```

Is there a way I can achieve this? Thanks!

**Comment by deini** [comment]
Not sure if its the right approach but I'm using Algolia's [react-element-to-jsx-string](https://github.com/algolia/react-element-to-jsx-string). You can also customize formatting, showing defaultProps, etc.

Something like:

```jsx
import reactElementToJSXString from 'react-element-to-jsx-string';
import {
  LiveProvider,
  LiveEditor,
  LiveError,
  LivePreview
} from 'react-live'

import myComponent from './mycomponent'

const code = const code = reactElementToJSXString(myComponent);

<LiveProvider code={code}>
  <LiveEditor />
  <LiveError />
  <LivePreview />
</LiveProvider>

**Comment by deini** [comment]
Not exactly what you are looking for but I've published a simple [webpack loader](https://github.com/deini/jsx-to-string-loader) that will transform delimited code to string. This way you can still write JSX and pass it as a string to `react-live`. The `README` on the repo has some examples on how to use it. Hope it helps.

**Comment by conradj** [comment]
That looks pretty cool @deini! Haven't had much chance to look at this recently but will try and give it a go in my Gatsby project.

**Comment by sofiapoh** [comment]
There's no plans to support anything but a string to be passed to `LiveProvider` as code for now, I'd recommend the solution @deini posted!
