### ISSUE TITLE
Can't edit padding of LiveEditor

### ISSUE THREAD

**Issue by claracmy** [FormidableLabs/react-live#157]
Are there any reasons why the padding of the LiveEditor is not style-able through a prop? 
```
 <Editor
        value={code}
        padding={10}
        highlight={this.highlightCode}
        onValueChange={this.updateContent}
        style={{
          whiteSpace: 'pre',
          fontFamily: 'monospace',
          ...baseTheme,
          ...style
        }}
        {...rest}
      />
```
It's stuck at 10px and adding padding in the style prop causes the cursor to be dislocated since the change isn't applied to the `textarea` of react simple code editor.

**Comment by nextriot** [comment]
So did you ever figure out how to remove the 10px padding? Would be nice to not have to open the same issue again.
