### ISSUE TITLE
Injecting code, without making it visible to user?

### ISSUE THREAD

**Issue by InventingWithMonster** [FormidableLabs/react-live#16]
Hi guys

I'm trying to write some online, editable examples with `react-live`. The framework is an animation framework not specifically related to React, but it's useful to use React to render the stuff we're animating.

In order to KISS and not to confuse the two frameworks it'd be helpful to be able to inject something like `render(<Component />)` at the top of every example, without making it visible to the user. I've tried a couple of approaches but to no success. Is there a recommended way I go about doing this?

**Comment by philpl** [comment]
Unfortunately there's currently no way of doing this. Would a `transformCode` prop on the Provider solve this for you, that accepts a transformer function that receives the user's code and can return different code?

**Comment by InventingWithMonster** [comment]
I've got a PR on the way with `applyTransform` already in the works - let me change it to `transformCode` and I'll commit in a couple hours!

**Comment by InventingWithMonster** [comment]
PR here: https://github.com/FormidableLabs/react-live/pull/17

**Comment by philpl** [comment]
Thanks, I'll publish a new minor version for you in a couple of minutes :) I'll update the TS typings before
