### ISSUE TITLE
Sucrase support

### ISSUE THREAD

**Issue by felipeleusin** [FormidableLabs/react-live#160]
Hi,

We currently use react-live at my company but we're heavy into TypeScript and not being able to provide TypeScript support in our Playgrounds was becoming an issue.

I've managed to change this by adopting sucrase instead of bublé. I believe sucrase has less browser support than bublé (it generates code that runs only in modern browsers) but on the upside it has support for compiling TS and Flow.

Would you be interested in a PR for this? I ended up refactoring most of the code for typescript as well. I know this is a lot and if there's no interested I can keep a fork of this.

Thanks for the great project!

**Comment by dionaditya** [comment]
I successfully porting sucrase to browser.

Here is example live editor using sucrase and react-ace
https://amazing-kepler-dd4349.netlify.app/

**Comment by jpdriver** [comment]
closing this as we've now switched to Sucrase as of [`v3.0.0-rc1`](https://github.com/FormidableLabs/react-live/releases/tag/v3.0.0-rc1)

we don't support TypeScript yet at the time of writing, but with the switch to Sucrase there's no longer any reason we couldn't enable TS transpilation in a future release.
