### ISSUE TITLE
upgrade prism-react-renderer

### ISSUE THREAD

**Issue by endiliey** [FormidableLabs/react-live#168]
# Motivation

prism-react-renderer is now v1. I think it will be nice to upgrade the deps
https://github.com/FormidableLabs/prism-react-renderer/releases

**Comment by sofiapoh** [comment]
Thanks! Would you like to open a PR for this? If not I'll update it asap.

**Comment by endiliey** [comment]
sure thing. will be happy to send a PR

**Comment by endiliey** [comment]
@sofiapoh done #169

**Comment by panjiesw** [comment]
Hi there,
any chance to release this version with upgraded `prism-react-renderer`?
