### ISSUE TITLE
Does not work with react 15

### ISSUE THREAD

**Issue by alasdairhurst** [FormidableLabs/react-live#170]
Not sure if this was intentional or not, but since 2.0.0 react-live has not worked with React 15. There's nothing mentioned in the changelog for 2.0.0 about any dropped support, but also the readme should probably point our the versions this is intended to work with ;)

https://codesandbox.io/s/lively-cookies-d7o42?fontsize=14

**Comment by MathieuVedana** [comment]
It does not work with React 15 as the Editor component uses React.Fragment !!!
May be other of React 15 issues are hidden in other components...

`import React, { Component, Fragment } from 'react';`
[https://github.com/FormidableLabs/react-live/blob/v2.2.2/src/components/Editor/index.js](url)

Please fix or tell us that it is no more React 15 compatible

**Comment by scottianstewart** [comment]
Since the release of 2.0.0, react-live no longer supports React 15. The readme has been updated to reflect React minimum versions

https://github.com/FormidableLabs/react-live#faq
