### ISSUE TITLE
Cannot find module 'react-live-master/demo/server.js'

### ISSUE THREAD

**Issue by ZhenHe17** [FormidableLabs/react-live#171]
I try to run demo use ```npm run dev```.
but there is an error: Cannot find module 'react-live-master/demo/server.js'

**Comment by sofiapoh** [comment]
Sorry, this is probably some crud left from the last refactor since the server has now been deleted. I'll fix this unless you'd like to open a PR?

**Comment by ZhenHe17** [comment]
I'll open a PR and fix this.
