### ISSUE TITLE
request: new release

### ISSUE THREAD

**Issue by donifer** [FormidableLabs/react-live#173]
🙏 When you guys get a chance, could we get a new release published on `npm`?  Would like to use some changes currently unreleased on `master`.

**Comment by rakannimer** [comment]
A new release would be very helpful. 

We're using `react-live` in `docz` and the version on npm (2.2.1) has a `prism-react-renderer` version that breaks when parsing tsx (fixed on master).

Anything we can do to help with the release ?

Thanks for the great work on this library (and others) !

**Comment by sofiapoh** [comment]
The new release is now published, thank you all for your patience!

**Comment by rakannimer** [comment]
Thank you @sofiapoh 🙏 !
