### ISSUE TITLE
Can't assign lambdas to variables within component 

### ISSUE THREAD

**Issue by cesalberca** [FormidableLabs/react-live#18]
Hello! I'm trying to use the following component within react-live:

```javascript
class Button extends React.Component {
  constructor() {
    super();

    this.state = {
      counter: 0
    };
  }

  // This is where the error seems to take place
  handleClick = () => {
    this.setState({
      counter: this.state.counter + 1
    });
  }

  render() {
    return (
      <button
        onClick={this.handleClick}
      >
        {this.state.counter}
      </button>
    );
  }
}
```

However I get the following error: 

```
SyntaxError: Unexpected token (10:13) 6 : counter: 0 7 : }; 8 : } 9 : 10 : handleClick = () => { ^
```

I would like to use this syntax as I don't need to bind in the constructor and for me it makes it more concise.

**Comment by philpl** [comment]
This is not supported by Bublé: https://buble.surge.sh/#class%20x%20%7B%0A%20%20help%20%3D%20()%20%3D%3E%20%7B%7D%0A%7D

And I believe it hasn't been implemented yet, as it's only reached stage 2 as of now.

Sorry :/
