### ISSUE TITLE
No clear code explanation of how to use `withLive`

### ISSUE THREAD

**Issue by anishagg17** [FormidableLabs/react-live#188]
please provide code examples of how to use `withLive`

**Comment by sofiapoh** [comment]
Most of our code examples live in the storybook for `react-live`, I'll make a note to add that to the `readme`. 
[See here](https://github.com/FormidableLabs/react-live/blob/master/stories/Live.js#L241) for the `withLive` story.

**Comment by anishagg17** [comment]
@sofiapoh where can i see these  stories live??

**Comment by sofiapoh** [comment]
If you clone the repository and spin up storybook you'll be able to see them:

```sh
npm i
npm run storybook:build
npm run storybook
```

**Comment by anishagg17** [comment]
Thanks @sofiapoh Very much now i am able to run `withLive` properly .
I will ping you in case i need more help

**Comment by sofiapoh** [comment]
Glad it's resolved!
