### ISSUE TITLE
react-live doesn't support import statements

### ISSUE THREAD

**Issue by anishagg17** [FormidableLabs/react-live#190]
@sofiapoh when i use code that contains import statements with `LiveProvider` it renders error .
Is there any way to prevent this from happening?

**Comment by sofiapoh** [comment]
We don't handle imports during the code transiplation in react-live. If you want to use code that's in another file/another library in react-live environment there's a whole section in the [readme about it ](https://github.com/FormidableLabs/react-live#how-does-the-scope-work).

**Comment by anishagg17** [comment]
@sofiapoh i mean i want to write 

        `import React from 'react';` 

or something like that in  the editor for my project , I too have seen the use of `scope` prop but How to display import statements??

**Comment by sofiapoh** [comment]
`react-live` doesn't handle adding import statements. All the code inside the editor gets transpiled and we cannot handle imports in this sandboxed environment. If you need to show the import statements for documentations sake I'd suggest you maybe comment them out and add a note for your users.
