### ISSUE TITLE
Changing 13px react-live font-size to 16px?

### ISSUE THREAD

**Issue by tr1s** [FormidableLabs/react-live#212]
I can't seem to figure out how to change the font-size for the Live Editor specifically. Could someone help me out?
   
<img width="586" alt="CleanShot 2020-07-07 at 20 22 27@2x" src="https://user-images.githubusercontent.com/19172250/86859513-cd469500-c090-11ea-987c-f5ab81bc4356.png">

```
<LiveProvider code={codeString} noInline={true}>
        <LiveEditor theme={dracula} padding={`15px`} fontSize={26} ???? />
        <LiveError />
        <LivePreview />
</LiveProvider>
```

Thanks, let me know!

**Comment by sofiapoh** [comment]
`LiveEditor` accepts a `style` prop which will allow you to override any of the default styles: 

```
    <LiveProvider code={codeString} noInline>
      <LiveEditor
        theme={dracula}
        padding="15px"
        style={{ fontSize: "16px", backgroundColor: "darkslateblue" }}
      />
      <LivePreview />
      <LiveError />
    </LiveProvider>
```

Hope this helps!

**Comment by tr1s** [comment]
> style={{ fontSize: "16px", backgroundColor: "darkslateblue" }}

Worked perfect, thank you!

**Comment by sofiapoh** [comment]
I've also updated the documentation to highlight this, I realised it wasn't mentioned there at all!
