### ISSUE TITLE
Words are being highlighted unlike normal text even on simple JSX code

### ISSUE THREAD

**Issue by markcnunes** [FormidableLabs/react-live#232]
The `as` is being linted unlike normal text even when it is inside a simple `<h3>` tag.

https://react-live.netlify.app/

![image](https://user-images.githubusercontent.com/18724600/102778044-bd461780-4389-11eb-8c12-ec31a08133a0.png)

Is there any solution for it?

**Comment by scottianstewart** [comment]
Can't recreate, closing issue.
