### ISSUE TITLE
Errors created post-transform aren't caught by react-live

### ISSUE THREAD

**Issue by andyrichardson** [FormidableLabs/react-live#233]
## About

Hey there! I think I've found a bug in react-live relating to transformation steps.

## Reproduction
 - Create a react live instance with some code
 - Add a transformCode step
 - Run the live instance and change the code to make a runtime error

### Expected result

Error is caught by react-live and is presented to the user

### Actual result

Error is not caught by react-live and containing app crashes.

![Kapture 2020-12-22 at 15 50 27](https://user-images.githubusercontent.com/10779424/102907172-8f3a0380-446d-11eb-918e-79e03ce97ce8.gif)

### Additional info

- This error does not occur when `transformCode` is not used
- There console warning looks to be due to react-live not properly tearing down react applications (an unrelated issue)

**Comment by srmagura** [comment]
May try to PR this as it is affecting us and looks easily solved. Hacktactular workaround:

```ts
export function transformCode(code: string): string {
  try {
    const result = Babel.transform(code, options).code
    if (!result) throw new Error('Babel failed to compile the code.')

    return result
  } catch (e) {
    // react-live doesn't currently handle errors thrown by `transform` functions.
    // So we catch the error and return code that renders that error.
    //
    // TODO Fix https://github.com/FormidableLabs/react-live/issues/233
    // and remove this hacky code.

    const message = (e as any).message
    const messageEscaped = message.replace(/`/g, '\\`') // Escape backticks
    return `render(<div style={{ whiteSpace: 'pre', fontFamily: 'monospace', color: '${colors.danger}' }}>{\`${messageEscaped}\`}</div>)`
  }
}
```
