### ISSUE TITLE
Object not valid as a React child crash

### ISSUE THREAD

**Issue by isaacbrodsky** [FormidableLabs/react-live#240]
Reproduction steps:

* Open https://react-live.netlify.app/
* Replace the content of the text editor with "{}"
* The page crashes and prints an error to the console referencing [this link](https://reactjs.org/docs/error-decoder.html/?invariant=31&args[]=object%20with%20keys%20%7BChildren%2C%20createRef%2C%20Component%2C%20PureComponent%2C%20createContext%2C%20forwardRef%2C%20lazy%2C%20memo%2C%20useCallback%2C%20useContext%2C%20useEffect%2C%20useImperativeHandle%2C%20useDebugValue%2C%20useLayoutEffect%2C%20useMemo%2C%20useReducer%2C%20useRef%2C%20useState%2C%20Fragment%2C%20Profiler%2C%20StrictMode%2C%20Suspense%2C%20unstable_SuspenseList%2C%20createElement%2C%20cloneElement%2C%20createFactory%2C%20isValidElement%2C%20version%2C%20unstable_withSuspenseConfig%2C%20__SECRET_INTERNALS_DO_NOT_USE_OR_YOU_WILL_BE_FIRED%7D&args[]=)

Any object being returned by the code block causes this issue - so typing "React" or "{}" into the text box causes this. I found this issue through Docusaurus which is also effected.

Could some test for objects that can't be rendered, or error handling be added, to prevent this from bringing down the entire page?

**Comment by SidRathi47** [comment]
Facing same problem

**Comment by jpdriver** [comment]
This seems to have been fixed in the releases since this was opened 🙇🏻‍♂️
