### ISSUE TITLE
simple usage example doesn't work in Vite

### ISSUE THREAD

**Issue by Adam-Collier** [FormidableLabs/react-live#243]
Hi guys I was just getting started with react-live in a Vite project and stumbled at the first hurdle. 

Having something like the below in App.jsx
```jsx
import React, { useState } from 'react';
import './App.css';
import { LiveProvider, LiveEditor, LiveError, LivePreview } from 'react-live';

function App() {
  return (
    <LiveProvider code="<strong>Hello World!</strong>">
      <LiveEditor />
      <LiveError />
      <LivePreview />
    </LiveProvider>
  );
}

export default App;
```
shows this error in the console:

![image](https://user-images.githubusercontent.com/20065745/115587862-0d949e00-a2c6-11eb-902d-e1bfe78fb4f4.png)

I've created a branch so you can check it out yourselves: https://github.com/Adam-Collier/vite-mdx-playground/tree/react_live_basic_example

I'm not sure if it's an ESM issue but any help would be much appreciated 😃

**Comment by LXSMNSYC** [comment]
I've stumbled upon this issue as well, however, this is an upstream issue: https://github.com/satya164/react-simple-code-editor/issues/86

**Comment by ruifortes** [comment]
https://github.com/satya164/react-simple-code-editor/issues/86
