### ISSUE TITLE
how to support live preview html ?

### ISSUE THREAD

**Issue by stfenjobs** [FormidableLabs/react-live#273]
# this is my code, it's a html code

how to support live preview html ?

thank you very much 

![image](https://user-images.githubusercontent.com/6580897/132132709-2f9ba289-1c50-4fa3-a163-aeffc891624f.png)

![image](https://user-images.githubusercontent.com/6580897/132132701-f56fdc84-1f5c-4b6c-9676-a183d2f48d08.png)

**Comment by stfenjobs** [comment]
in the demo:

https://react-live.netlify.app/

i write code:
```

<h1>1111</h1>
<h2>2222</h2>
```

i got error,

how to make it to support html live 

thank you very much

![image](https://user-images.githubusercontent.com/6580897/132133204-113c7d64-9f4d-461f-8262-833fc28c1551.png)

**Comment by DelphiCoder** [comment]
As the error states, you must wrap your components/tags at the **root** level.  Only  **ONE** root element is permitted under react.  You could place your H1 and H2 tags within an enclosing DIV.  Or you can use the empty tag <> like so:

```html
<>
<h1>1111</h1>
<h2>2222</h2>
</>
```
or simply use a DIV:

```html
<div>
<h1>1111</h1>
<h2>2222</h2>
</div>
```

**Comment by stfenjobs** [comment]
@DelphiCoder  tks
