### ISSUE TITLE
Option to disable Buble

### ISSUE THREAD

**Issue by ntucker** [FormidableLabs/react-live#274]
1) It's destructive as it transforms away classes, which means it this is all anyone sees: `class constructors must be invoked with 'new'`
2) It's completely pointless except for JSX as there are zero developers in the world running IE11 as their primary browser.
3) It's expensive to process and download
4) There are better ways to deal with JSX

If you like this default - whatever. Just give us the option to be able to use this project. It comes with docusaurus so the stylings are nice.

I tried

```
        transpileOptions={{
          target: { chrome: 71 },
          transforms: { classes: false },
        }}
```

to no avail

**Comment by jpdriver** [comment]
hey @ntucker -- we'll be replacing Bublé with [sucrase](https://github.com/alangpierce/sucrase) going forward. there still isn't a way to disable the transpilation step, but you may find that it's less destructive.

i'm going to close this issue for now, but please reopen it if you're still experiencing the issue. thanks! 🙇🏻‍♂️

**Comment by ntucker** [comment]
Could we have options for this? Would be great to use the already shipped with bundle typescript transform. I mean who doesn't use typescript? `disableESTransforms: true ` would also be handy here
