### ISSUE TITLE
import some package build in webpack5  federation module , react-live execute the code ,show some error below

### ISSUE THREAD

**Issue by daring123** [FormidableLabs/react-live#275]
why? 

![image](https://user-images.githubusercontent.com/5986074/132706700-4b9360bd-6d58-4536-81de-711f2f3107f4.png)

**Comment by jpdriver** [comment]
@daring123 can i ask you to try v3.0.0-rc1?

you can install using

yarn add react-live@next
i'd be really grateful for any feedback. thank you! 🙇🏻‍♂️
