### ISSUE TITLE
allow disabling theme

### ISSUE THREAD

**Issue by konsumer** [FormidableLabs/react-live#276]
I use my own CSS for prisma, and disable the theme for `prism-react-renderer` with `theme={undefined}` so it will just set the classes, but not style things, inline. This allows me to respect user's dark-mode preference, for example, by loading different imports under a media-query.  I tried same with `LiveProvider` and it did not work.

this works (disables theme, uses only prisma classes):

```jsx
const CodeView = ({ children, language, ...props }) => {
  return (
    <Highlight {...defaultProps} code={children} language={language} theme={undefined} {...props}>
      {({ className, style, tokens, getLineProps, getTokenProps }) => (
        <pre className={className} style={style}>
          {tokens.map((line, i) => (
            <div key={i} {...getLineProps({ line, key: i })}>
              {line.map((token, key) => (
                <span key={key} {...getTokenProps({ token, key })} />
              ))}
            </div>
          ))}
        </pre>
      )}
    </Highlight>
  )
}
```

this does not (uses inline style):

```jsx
const LiveCode = ({ children, ...props}) => (
  <LiveProvider code={children}  theme={undefined} {...props}>
    <LiveEditor />
    <LiveError />
    <LivePreview />
  </LiveProvider>
)
```

here is the outputted HTML:

```html
<textarea class="npm__react-simple-code-editor__textarea" autocapitalize="off" autocomplete="off" autocorrect="off" spellcheck="false" data-gramm="false" style="margin: 0px; border: 0px; background: none; box-sizing: inherit; display: inherit; font-family: inherit; font-size: inherit; font-style: inherit; font-variant-ligatures: inherit; font-weight: inherit; letter-spacing: inherit; line-height: inherit; tab-size: inherit; text-indent: inherit; text-rendering: inherit; text-transform: inherit; white-space: pre-wrap; word-break: keep-all; overflow-wrap: break-word; position: absolute; top: 0px; left: 0px; height: 100%; width: 100%; resize: none; color: inherit; overflow: hidden; -webkit-font-smoothing: antialiased; -webkit-text-fill-color: transparent; padding: 10px;">&lt;button&gt;COOL&lt;/button&gt;
</textarea>
```

for this:

```html
<button>COOL</button>
```

**Comment by konsumer** [comment]
I think issue might be [here](https://github.com/FormidableLabs/react-live/blob/master/src/components/Editor/index.js#L32).

instead of a `props.theme || liveTheme` maybe a check for `undefined`. I can add a PR, if there is interest.

**Comment by srmagura** [comment]
I found a way to disable the default theme that you can use in the meantime:

```tsx
const noTheme: EditorProps['theme'] = {
  plain: {},
  styles: []
}

render(<LiveEditor theme={noTheme}  />)
```

**Comment by jpdriver** [comment]
hey @konsumer -- for the current API, the workaround provided by @srmagura is the correct way to completely avoid the default theme.

could definitely see that changing in future, but as there's a way of doing this today i'm going to close this issue for now.

**Comment by konsumer** [comment]
> could definitely see that changing in future, but as there's a way of doing this today i'm going to close this issue for now.

Yeh, that works for me. The idea of a "totally empty theme" seems totally fine.
