### ISSUE TITLE
Best way to get up-to-date code

### ISSUE THREAD

**Issue by joshuacrowley** [FormidableLabs/react-live#28]
I'm hoping to save the current code as a string in a state on a parent. Figured I'd use the onChange callback, like this

`					<LiveEditor
						onChange={newCode => {
							this.setState({ code: newCode });
						}}
					/>
`

This works, but then the live editor silently stops updating and I'm not sure why – might be a React knowledge gap of mine. Any suggestions? Thanks!

**Comment by sergiodxa** [comment]
You need to pass the `this.state.code` value to `LiveProvider` as the prop `code`
```js
<LiveProvider code={this.state.code}>
  <LiveEditor onChange={newCode => { this.setState({ code: newCode }); }} />
</LiveProvider>
```
Something like that.

**Comment by grrowl** [comment]
Does this ^ actually work? The docs seem to imply `code=` is only for the initial render, a bit like `defaultValue=`. I've been re-setting the state using something like `key={this.state.codeKey}` which changes when the code does.

**Comment by sofiapoh** [comment]
I wasn't able to reproduce this issue with updates so I'm closing this issue for now, if this is still a problem please let me know!
