### ISSUE TITLE
LivePreview isn't working on IE11

### ISSUE THREAD

**Issue by msankaran0712** [FormidableLabs/react-live#282]
LivePreview isn't rendering on IE11, even your demo site is facing the same issue

![image](https://user-images.githubusercontent.com/50131391/138754400-0ef6e110-78ca-4e6a-9377-bc94c8bd4721.png)

**Comment by jpdriver** [comment]
hey @msankaran0712 -- unfortunately we've stopped supporting IE11. This will be noted as a breaking change in the next major release.

> There are known issues in IE 11 due to the `MutationObserver` method being unable to read text nodes that have been removed via the `contenteditable`.

(see https://github.com/FormidableLabs/use-editable#browser-compatibility)
