### ISSUE TITLE
Typing console or window crashes the editor

### ISSUE THREAD

**Issue by charj** [FormidableLabs/react-live#283]
I noticed something when doing some UAT within our project. At first, we assumed it was within our implementation, however, since testing the live demo - the issue persists there too.

Steps to recreate:

1. Visit: https://react-live.netlify.app/
2. Nullify any editor
3. Type `console` or `window`
4. Upon finishing typing, the entire page will crash and throw an error to the console

In development mode, more information is shown in the console.

I'm happy to provide more information if needed.

Thanks
![Selection_003](https://user-images.githubusercontent.com/655807/138862037-7febbe4e-f1b6-43fe-8e8f-653a07b07a97.png)

**Comment by ryan-roemer** [comment]
Confirmed. This does crash the whole page / app.

**Comment by charj** [comment]
Amazing, thank you @AaronPowell96.

@jpdriver, any idea when a new version will be released containing this fix, please?

**Comment by jpdriver** [comment]
this is available in `react-live@2.4.1` or more recent. at this stage you can just `yarn add react-live` and it'll be there

**Comment by charj** [comment]
Updated our project.

Thanks all involved
