### ISSUE TITLE
API to display/style static, uneditable code in LiveEditor

### ISSUE THREAD

**Issue by geoffdavis92** [FormidableLabs/react-live#29]
As @philpl and I discussed in [this styled-components issue](https://github.com/styled-components/styled-components-website/issues/51), it would be great to have a header/footer section where static, un-editable code provided by the library user could be displayed.

This would be useful for code that users want to display as contextually important to the code that end-users can edit, while keeping the contextual code itself un-editable.

Specific to the `styled-components` case, the static, unevaluated code would show that one needs to import a helper named export, instead of relying solely on the main library.

My demo in React-Live's Storybook environment:

---

[![GIF showing static header section of a React-Live editor component ](https://media.giphy.com/media/3o7aCURp6pqbaS6w3m/giphy.gif)](https://media.giphy.com/media/3o7aCURp6pqbaS6w3m/giphy.gif)

---

I ran a test and nothing broke, though I have not yet written any tests specific to the addition of the new `staticCode` prop.

Feel free to review/comment on my edits on [my fork](https://github.com/geoffdavis92/react-live/tree/pr).

Thanks!

EDIT: worth noting that this is a rough sketch, and ~~obviously~~ only one possible way to enable this feature.

**Comment by philpl** [comment]
Hiya, sorry after looking at this again I realised that we don't need to implement this here if we only want to display some import statements. We can simply display a CodeBlock above the editor on the styled-components-website.

Sorry, but I think this doesn't add a lot of value in this case to react-live. Maybe you're interested in implementing something similar with `CodeBlock` on the website?
