### ISSUE TITLE
3.0.0 - codesandbox template for bug reports

### ISSUE THREAD

**Issue by stevenocchipinti** [FormidableLabs/react-live#301]
Hello,

Thanks for releasing `3.0.0`, it looks great!

Following #281, I can see how having a codesandbox link can really help with bug reports.
I am currently trying out `3.0.0` and _may have_ discovered another bug but then I couldn't seem to get `3.0.0` working in codesandbox either.

My questions are:
* What am I doing wrong with [this codesandbox](https://codesandbox.io/s/react-live-3-0-0-tgoeb)?
* Is it worth adding a working codesandbox link to the readme or contributing guide to ease future bug reports?

For reference, I:
* Created a new React codesandbox
* Installed `react-live@3.0.0`
* Used the sample code from the readme

Which results in this error:
![Screen Shot 2022-02-09 at 3 55 04 pm](https://user-images.githubusercontent.com/790066/153124571-3b2d0b29-4768-42f4-a6b3-92c3d318d751.png)

Once I can create a codesandbox, I'll try to reproduce the bug there and open a new issue.

**Comment by robberfree** [comment]
+1, even updated the react-scripts to v5.0.0. same issues.

**Comment by nihgwu** [comment]
for CRA [here](https://github.com/nihgwu/react-runner/blob/master/examples/with-cra/config-overrides.js#L2-L7) is the fix
