### ISSUE TITLE
disable spellcheck in v3

### ISSUE THREAD

**Issue by lukesmurray** [FormidableLabs/react-live#310]
![image](https://user-images.githubusercontent.com/34020210/160174954-cc8cf011-c301-4fbc-9571-ab48ff3d4a26.png)

v3 doesn't set spellcheck to false. v2 did see #30

**Comment by raulfdm** [comment]
@jpdriver this fix is already published? I'm running 3.1 and it's still an issue.

**Comment by mryechkin** [comment]
Would like to know this as well, as I'm also still seeing this behaviour on `3.1.0`

**Comment by jpdriver** [comment]
oops 😅 sorry about that folks -- it was merged into `master` but never released!

it's available now in [`v3.1.1`](https://github.com/FormidableLabs/react-live/releases/tag/v3.1.1), and you can grab it using `yarn add react-live@next`
