### ISSUE TITLE
Any way to add Sucrase options ?

### ISSUE THREAD

**Issue by jonathangerbaud** [FormidableLabs/react-live#317]
Hello,

I'm trying to use react-live but my code is using a custom JSX transform.

Is there any way I could set the jsxPragma and jsxFragmentPragma options for Sucrase?

In their doc, Sucrase indicates you can customize the jsx transform function:

```
JSX Options
Like Babel, Sucrase compiles JSX to React functions by default, but can be configured for any JSX use case.

jsxPragma: Element creation function, defaults to React.createElement.
jsxFragmentPragma: Fragment component, defaults to React.Fragment.
```

Thank you very much.

**Comment by nihgwu** [comment]
I added those options to [`react-runner`](https://github.com/nihgwu/react-runner) before, but I reverted the change, as you can override it by `scope={{React: {...React, createElement: YourJsx, Fragment: YourFragment}}`

**Comment by jonathangerbaud** [comment]
OK thanks!
