### ISSUE TITLE
how to set code in LiveEditor that isn't used? 

### ISSUE THREAD

**Issue by ghost** [FormidableLabs/react-live#329]
```
code: `class MarkdownEditor extends React.Component {\n\tconstructor(props) {\n\t\tsuper(props);      
```

![image](https://user-images.githubusercontent.com/20955623/189739931-617a618c-90c5-4a0e-9c19-7aa6ffd05f4c.png)

Yes. I'm re-creating reactjs.org website. its been a real joy so-far :)

**Comment by stephyswe** [comment]
ah found one way. edit the theme with plain: {tabSize: '12px' } , neat :)

**Comment by stephyswe** [comment]
is it possible to add code that doesn't run in live editor? 
example:

import styled from 'styled-components
const Header = () => {
return <div>text</div>
}
``` 
and only run the const code, and not the import line.
