### ISSUE TITLE
Is it possible to add tailwindcss as a scope to my rendered react components? 

### ISSUE THREAD

**Issue by mfts** [FormidableLabs/react-live#350]
I'm using react-live inside a Next.js@13.3 application. I use tailwindcss to style my entire page. The source code I want to render with react-live also contains tailwindcss utility classes, however, they are not rendered. 

I saw in the API there's a `scope` parameter. Is it possible to somehow add tailwind there? 

I haven't found any other question related to this. I'd love your help in figuring this out. 

Thank you

**Comment by carloskelly13** [comment]
Hi :wave: This is good idea, let us think of some ways to make this work. Thanks for bringing it up!
