### ISSUE TITLE
Tab normalization breaks Safari

### ISSUE THREAD

**Issue by gaearon** [FormidableLabs/react-live#37]
We are seeing broken indentation in Safari:

<img width="431" alt="screen shot 2017-09-27 at 8 07 21 pm" src="https://user-images.githubusercontent.com/810438/30932840-a2e0d932-a3c0-11e7-801a-5b5cbdbd35f8.png">

This happens because [normalization replaces spaces with tabs](https://github.com/FormidableLabs/react-live/blob/ed390f5ea5a084c3e2d447147d619ec0c9d10108/src/utils/normalizeCode.js#L3).

For now we'll fork and fix the normalization to use spaces, but I hope this can be solved upstream :-)

**Comment by philpl** [comment]
@gaearon I finally got around to fix this. Do you want to take a look at #42?
