### ISSUE TITLE
Warning: LiveProvider: Support for defaultProps will be removed from function components in a future major release. Use JavaScript default parameters instead.

### ISSUE THREAD

**Issue by stivenm16** [FormidableLabs/react-live#378]
Minimal set up following docs using Next.js 14:

![image](https://github.com/FormidableLabs/react-live/assets/92546021/e772a49e-4860-4776-a5c8-164627e975a0)

It's working properly but it's displaiyng this error:

![image](https://github.com/FormidableLabs/react-live/assets/92546021/a8ed71b1-0476-43b8-9484-385f4fe3bde5)

By now I can hide the warning using this: 
![image](https://github.com/FormidableLabs/react-live/assets/92546021/e84ad7ef-8550-422c-b1e0-ae7cc14bb93e)

any solution?

**Comment by moshie** [comment]
https://github.com/FormidableLabs/react-live/issues/339

Looks like there is a PR but it's not merged yet
