### ISSUE TITLE
cannot live preview typescript code

### ISSUE THREAD

**Issue by dinesh-matta-mpf** [FormidableLabs/react-live#45]
Hi,

I have a typescript application with react, when I am using this lib to preview typescript code I am getting error. Errors are specifically for braces. I am passing complete react container class(in typescript) to code attribute for "LiveProvider" component.

If you can give me any pointers on how do I use this plugin with typescript project, that would be helpful.

**Comment by philpl** [comment]
This project uses `buble` and thus doesn't support Typescript.

I don't think it'll ever support it as it's kind of unrealistic to maintain typings and a Typescript transpiler (if that exists in a similar browser-ready form) for a live-editing app.
