### ISSUE TITLE
HOC should pass props?

### ISSUE THREAD

**Issue by bs1180** [FormidableLabs/react-live#48]
Thanks for a great tool!

I think the [expected behaviour](https://reactjs.org/docs/higher-order-components.html#convention-pass-unrelated-props-through-to-the-wrapped-component) for a HOC is to pass external props through untouched, which I notice the `withLive` component doesn't. Would you be open to adding it, or is there a reason not to?

**Comment by philpl** [comment]
@bs1180 Oh true! great catch.

I'm not using the HOC in any project right now so I haven't it. Mind submitting a PR please, I can also fix it later if you're busy?
