### ISSUE TITLE
Documentation improvements

### ISSUE THREAD

**Issue by lilybarrett** [FormidableLabs/react-live#52]
My team and I ultimately wound up _loving_ react-live but struggled initially with familiarizing ourselves with the library. The provided code example should be clearer and more fleshed out, i.e., when it comes to providing props to a documented component, so users can be more productive with the library right off the bat.

**Comment by lilybarrett** [comment]
#53

**Comment by philpl** [comment]
Thanks a lot! I hope this will make it easier for others to get it up and running
