### ISSUE TITLE
Add `es/` (ESM) output for webpack consumtion

### ISSUE THREAD

**Issue by ryan-roemer** [FormidableLabs/react-live#56]
Aka `modules: false` for `babel-preset-env` for one output dir.

**Comment by kitten** [comment]
Just checked and it seems that React Live is already being distributed with an ES bundle.

However, I’d like to add a CJS flat bundle too instead of pointing to the lib folder which is what a lot of libraries I’m having an eye on are doing to prevent unexpected behaviour and minificarion quirks
