### ISSUE TITLE
Errors thrown by components from scope aren't caught

### ISSUE THREAD

**Issue by brianokeefe** [FormidableLabs/react-live#58]
It appears that if a component is included via the scope prop on `LiveProvider`, errors thrown by that component aren't caught by the `LiveProvider` to be displayed nicely by `LiveError`.

For the following component:

```
const App = (props) =>
  <LiveProvider code="<div>{ (() => {const a = 1; return a.substring() })() }</div>">
    <LiveError />
    <LivePreview />
  </LiveProvider>;
```

...the error is caught and displayed via `LiveError`, as expected. However, if you instead use a component included from scope, like so:

```
const components = {
  Foo: (props) => {
    const a = 1;
    return a.substring();
  },
}

const App = (props) =>
  <LiveProvider code="<Foo/>" scope={components}>
    <LiveError />
    <LivePreview />
  </LiveProvider>;
```

...the error is not caught and bubbles all the way up. It would be great if these kinds of errors could be caught and displayed by `LiveError`!

**Comment by kitten** [comment]
React Live is currently not using React v16’s error boundaries since it started for React 15 before.

I haven’t gotten around to implementing this yet, but PRs are very much appreciated if you’ve got some time 👍

**Comment by iosifnicolae2** [comment]
Did https://github.com/FormidableLabs/react-live/commit/67f5215e1f5f628f348e9833b2edd9db5266889e fixed the problem?

I can still reproduce the problem.. Any idea on how can I solve it?

Thanks!
