### ISSUE TITLE
Error rendering JSX with string values

### ISSUE THREAD

**Issue by alasdairhurst** [FormidableLabs/react-live#62]
I use react-live alongside react-storybook for static page builds. This was working until sometime recently.

Now all the static builds have the following error (shown in the LiveError component)
```ReferenceError: str is not defined```

You can see it here:
![image](https://user-images.githubusercontent.com/8441810/36595433-0be102a6-189a-11e8-873f-93c34ab155c7.png)

Note - this only happens when string JSX node children are used. An empty ```<div/>``` does not throw the error.

This also does not happen when running with react-storybook running as a server. Only when generating a static site.

This worked in 1.7.1 and has been broken sometime after.  I tested by reverting to 1.7.1 and it started working again.

There was something that I found could be improved aside from the error fix.
The error has no stack information and is pretty useless. The error possibly came from somewhere within buble. Unfortunately, even though logging the stack information helped a little bit, since the site was static, the code was minified so wasn't perfect. Either way, a console error of the stack track here could help people in the future:
https://github.com/FormidableLabs/react-live/blob/76cfe4df3c142055b62ef894ec145d0f9d71595b/src/components/Live/LiveProvider.js#L73

stack trace:
```
ReferenceError: str is not defined
    at Node.transpile (preview.17df648ff3ba4de8f974.bundle.js:1)
    at Array.isArray.value.forEach.node (preview.17df648ff3ba4de8f974.bundle.js:1)
    at Array.forEach (<anonymous>)
    at Node.transpile (preview.17df648ff3ba4de8f974.bundle.js:1)
    at Node.transpile (preview.17df648ff3ba4de8f974.bundle.js:1)
    at Node.transpile (preview.17df648ff3ba4de8f974.bundle.js:1)
    at Node.transpile (preview.17df648ff3ba4de8f974.bundle.js:1)
    at Array.isArray.value.forEach.node (preview.17df648ff3ba4de8f974.bundle.js:1)
    at Array.forEach (<anonymous>)
    at Node.transpile (preview.17df648ff3ba4de8f974.bundle.js:1)
```
Looks like it's possibly Buble. Can't be sure...

**Comment by alasdairhurst** [comment]
@kitten  The buble upgrade looks like it broke something else. Now it fails to even build:

```
> build-storybook -c .storybook -o pages

info @storybook/react v3.3.14
info
info => Loading custom .babelrc
info => Loading custom addons config.
info => Loading custom webpack config (extending mode).
info Building storybook ...
ERR! Failed to build the storybook
ERR! Module not found: Error: Can't resolve 'buble/dist/buble.deps' in 'C:\myProject\node_modules\react-live\lib\utils\transpile'
```

**Comment by kitten** [comment]
@alasdairhurst Is that with 1.10.1? We're not importing buble from `buble/dist/buble.deps` anymore: https://github.com/FormidableLabs/react-live/blob/master/src/utils/transpile/transform.js#L1

**Comment by alasdairhurst** [comment]
It's definitely 1.10.1. I hardcoded the version and checked the package.json.

This is what I see in /lib/utils/transpile/transform.js

```
'use strict';

exports.__esModule = true;
exports._poly = undefined;

var _buble = require('buble/dist/buble.deps');

var _assign = require('core-js/fn/object/assign');

var _assign2 = _interopRequireDefault(_assign);

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

var _poly = exports._poly = { assign: _assign2.default };

var opts = {
  objectAssign: '_poly.assign',
  transforms: {
    dangerousForOf: true,
    dangerousTaggedTemplateString: true
  }
};

exports.default = function (code) {
  return (0, _buble.transform)(code, opts).code;
};
```

**Comment by kitten** [comment]
@alasdairhurst the `lib/` folder is indeed still in the tarball of `1.10.1`. Sorry about that! However, that's not even supposed to be in use.

The `package.json` is pointing to the flat bundles in the `dist/` folder: https://github.com/FormidableLabs/react-live/blob/master/package.json#L5-L8

Are you maybe linking to the `lib/` folder manually, by any chance?

**Comment by alasdairhurst** [comment]
Yup, that's it.
```
import LiveError from 'react-live/lib/components/Live/LiveError';
import LivePreview from 'react-live/lib/components/Live/LivePreview';
import LiveProvider from 'react-live/lib/components/Live/LiveProvider';
```
At first I couldn't remember why i was doing that... Maybe performance with selective imports.

Then i remembered. It was during the time i was debugging this original issue. I wasn't going to try and modify the minified src for logging the error out, so I imported the lib and edited that instead. 

I will test importing it using the supported way and get back to you if it breaks :)
