### ISSUE TITLE
How to pass function in scope in LiveProvider?

### ISSUE THREAD

**Issue by bipin244** [FormidableLabs/react-live#71]
Hello friend,
First of all thanks for the nice plugin, it's work really very well.
Now I have some question about my requirement I need to check my newly created component and I have passed some on change function required in my prototype.
So can anyone help me please to pass a function in LiveProvider code?

**Comment by kitten** [comment]
You can literally just do the following:

```js
const scope = {
  doSomething: () => { /* ... */ }
};

return (
  <LiveProvider code={code} scope={scope}>
   /* ... */
  </LiveProvider>
);
```

This exposes `doSomething` in this example globally in the scope of the code that `LiveProvider` will run.

Also, please describe your issue more in detail next time :wink:

**Comment by kitten** [comment]
@bipin244 you mean you'd like to pass a callback into the scope? Yes, that's completely possible

**Comment by bipin244** [comment]
so can you give me any example or description for this, please?
