### ISSUE TITLE
Question: Is there a way to load the Custom Class plugin with Prism?

### ISSUE THREAD

**Issue by hbuchel** [FormidableLabs/react-live#75]
Is there an existing way to load the Custom Class Prism plugin or pass options to it from react-live? (https://prismjs.com/plugins/custom-class/)
Use case: I was previously using Prism to show static code samples, and this plugin allowed me to prefix the CSS class names output by Prism so that the more generic-ey class names such as "token" and "tag" don't get in the way of my existing styles.

**Comment by sofiapoh** [comment]
Closing this here as we are now highlighting the code with (`prism-react-rendrer`)[https://github.com/FormidableLabs/prism-react-renderer#theming] instead of just Prism but if you still have this problem I'd suggest opening this issue in `prism-react-renderer` repo!
