### ISSUE TITLE
How to be notified when errors happen?

### ISSUE THREAD

**Issue by alansouzati** [FormidableLabs/react-live#92]
I want to conditionally render a node if there is an error, currently `LiveEditor` does not notify me if an error happens, it would be nice if it did.

**Comment by sofiapoh** [comment]
If you mean inline errors there are plans to support that in a future version of react-live 🙂

**Comment by kitten** [comment]
Apart from this the errors will never be sourced from the editor but from the Provider since the Provider does the transpiration. The runtime errors however are reported from the Preview component and are passed up to the provider
