### ISSUE TITLE
Document babel usage and `transformCode` option

### ISSUE THREAD

**Issue by sw-yx** [FormidableLabs/react-live#93]
currently the only docs on it is the PR that added it: https://github.com/FormidableLabs/react-live/pull/17

would love more examples, in particular applying a babel plugin as it seems react-live doesn't use babel on the given code.

EDIT: just found https://github.com/FormidableLabs/react-live/issues/67 which shows how to use babel...

**Comment by sofiapoh** [comment]
Hi! We're currently working on the next version of react-live and some of the documentation will have to be updated due to API changes, I'll keep this in mind when the time comes!

**Comment by sw-yx** [comment]
thanks!

**Comment by sebastienfi** [comment]
@sofiapoh Hi! Do you have a rough ETA on this next version?
