### ISSUE TITLE
attr-value not being applied to values with spaces

### ISSUE THREAD

**Issue by sgullen** [FormidableLabs/react-live#95]
Sorry if this is already addressed but I have very limited knowledge in how these property values are being parsed and am trying to simply get the "attr-value" class applied to values with a space. Pictured below is what I'm currently seeing:

https://imgur.com/a/BKBJmP5

I appreciate any help on this. Thanks.

**Comment by ludovicmnji** [comment]
I noted the same issue and it's visible on the demo.

![capture d ecran 2019-03-05 a 10 38 38](https://user-images.githubusercontent.com/6171841/53795780-faca7e00-3f32-11e9-9339-7d8bd5413f2b.png)

Maybe it's a problem with PrismJS ?

**Comment by sofiapoh** [comment]
I haven't been able to reproduce this issue anymore, I think it was solved when we started using `prism-react-renderer` for highlighting. If you still have this problem let me know!
