### ISSUE TITLE
Allow passing options to buble

### ISSUE THREAD

**Issue by jquense** [FormidableLabs/react-live#96]
AT the moment there is no way to control what buble compiles. I don't want it to compile taggedTemplateStrings, b/c it compiles it poorly and breaks usage in emotion. using `transformCode` isn't feasible, the code is still passed to buble after i compile it, and since i want to leave the uncompiled template tags it just compiles them later.

**Comment by zslabs** [comment]
@jquense Ever find out a way around this? @sofiapoh Any thoughts?

**Comment by aleclarson** [comment]
See #199 for an implementation
