### ISSUE TITLE
[Request][Discussion] Adding React.Fragment automatically

### ISSUE THREAD

**Issue by lucantini** [FormidableLabs/react-live#97]
One question that popped out while developing a sandbox with react-live is why can I only render a single element. This is obvious, react-live just gets the React code and renders it, and a React Component can only render a single element.

Wouldn't it be a good idea to always wrap the  contents of the render inside of a React.Fragment? This way, scenarios like this:
```jsx
<TextComponent>
    Text Content!!!
</TextComponent>
<ButtonComponent>
    Button Content!!!
</ButtonComponent>
```
Would render like _magic_

Maybe this behavior would not be what you guys are looking for, and would be too **magical**.

Hope we can discuss about it!

**Comment by sofiapoh** [comment]
I think this is probably not something we'll do for now at least. A lot of people use `react-live` to add interactivity to their documentation and to add any 'magic' to that from our side might cause confusion. Happy to hear counterarguments though!

**Comment by philholden** [comment]
@lucantini You can do this by implementing your own editor that wraps code in a string:

```javascript
import React from "react";
import { Editor, withLive } from "react-live";

class WrapCode extends React.Component {
  static defaultProps = {
    wrapCode: x => x
  };

  constructor(...args) {
    super(...args);
  }

  onChange = code => {
    const { live, wrapCode } = this.props;
    if (live && live.onChange) {
      live.onChange(wrapCode(code));
    }
  };

  componentDidMount() {
    const { live } = this.props;
    this.onChange(live.code);
  }

  render() {
    const { onChange, wrapCode, style, live } = this.props;
    return <Editor onChange={this.onChange} code={live.code} style={style} />;
  }
}

export const WrapCodeEditor = withLive(WrapCode);
```
then:

```javascript
const MyEditor = props => <WrapCodeEditor
  wrapCode={text => `<React.Fragment>{text}</React.Fragment>`}
  {...props}
/>
```

@sofiapoh it would be nice if the provider allowed you to define a wrapCode or mapCode function. As triggering the onChange on the editor componentDidMount is a bit late. In examples I often have the need to add a div with padding or alignItems or flexDirection.

**Comment by tujoworker** [comment]
I submitted a pull request for this: #112 hope a maintainer will have a look at it.

**Comment by sofiapoh** [comment]
I've added an example on the PR on how to achieve this with existing functionality: https://github.com/FormidableLabs/react-live/pull/112#issuecomment-470470297
