### ISSUE TITLE
[Question] Paste event listener 

### ISSUE THREAD

**Issue by lucantini** [FormidableLabs/react-live#99]
In the specific case of our documentation we are trying to paste some Components in the `LiveEditor` programmatically! The thing is that the `LiveEditor` doesn't listen for the change event, it only listen to keyDown and keyUp. 

Is it a possibility to add a change listener that actually changes the content? Like, when I use the onChange callback that it's provided, it's not called during the paste event :/ - though paste usually calls the onChange handler.

**Comment by kitten** [comment]
Why don't you just wrap the provider and pass in a new value? :)

That's a good point though on the other hand. We're still pending and performing a big refactor for which the next version will use an entirely different editor setup
